# Site settings
title: Sanchit's Blog 
email: sanchit.agrawal@gmail.com
description: > # Writer Theme is a responsive template
Sanchit is a seasoned architect
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sanchitagrawal.com/" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  About : ['Sanchit Agrawal', 'http://www.sanchitagrawal.com/', 'fa-user']
  Author : ['Author', '/author/sanchit', 'fa-user']
  Contact : ['Contact', '/contact', 'fa-plane']
single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
 #   Writer: ['Writer 2016', '/about']


# Build settings
# markdown: kramdown
