# Site settings
title: Sanchit's Blog 
email: sanchit.agrawal@gmail.com
description: > # Writer Theme is a responsive template
 Sanchit is a seasoned Cloud Architect with extensive experience in IOT, Big Data and Middleware Technologies
baseurl: "" # the subpath of your site, e.g. /blog
plugins: ['jekyll-twitter-plugin']
url: "http://www.sanchitagrawal.com/" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  About : ['Sanchit Agrawal', 'http://www.sanchitagrawal.com/', 'fa-user']
  Author : ['Author', '/author/sanchit', 'fa-user']
  Contact : ['Contact', '/contact', 'fa-plane']
single_footer: '<p>Keep on Rocking in the free world \m/ <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']

# Build settings
# markdown: kramdown
